### ISSUE TITLE
Right clic not working on search results

### ISSUE THREAD

**Issue by dubicube** [securingdata/smartsafe-client-desktop#10]
Client version: 1.0.4
Steps to produce:
- Search for an entry
- Right clic on one of the entry resulted from the search
- Nothing happens
What I expect: Having the same contextual menu we get if we right clic on an entry in a group.

Here is the stacktrace I get while producing the bug:

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at fr.securingdata.smartsafe.controller.Controls.getCurrentSelectedGroupForUse(Controls.java:655)
        at fr.securingdata.smartsafe.view.GlobalView.lambda$getTableEntries$85(GlobalView.java:311)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene.processMenuEvent(Scene.java:1802)
        at javafx.scene.Scene.access$4500(Scene.java:159)
        at javafx.scene.Scene$ScenePeerListener.menuEvent(Scene.java:2516)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$null$3(GlassViewEventHandler.java:466)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMenuEvent$4(GlassViewEventHandler.java:449)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:410)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMenuEvent(GlassViewEventHandler.java:448)
        at com.sun.glass.ui.View.handleMenuEvent(View.java:563)
        at com.sun.glass.ui.View.notifyMenu(View.java:889)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:187)
        at java.lang.Thread.run(Unknown Source)

**Comment by securingdata** [comment]
Fixed in v1.0.5
