### ISSUE TITLE
UI frozen when copying password (but only when the planets are aligned)

### ISSUE THREAD

**Issue by dubicube** [securingdata/smartsafe-client-desktop#8]
I don't understand exactly when the bug occurs, but I saw it at least 2 times, and I cannot intentionally re-produce it.
As I could not replicate it on the first time, I did not reported it, and I don't remember exactly what I did to produce it. But here is what I did on the second time:
- Plug in the card reader
- Unlock the card through the client
- Search for an entry with ctrl-f feature
- Copy password with ctrl-c
- Keep the client in the background (enough time to let the client auto-disconnect from the card).
- Copy/paste some text in other windows/applications (especially from and to a putty terminal) (maybe an important detail, or maybe not...)
- Go back to the client, and unlock again the card
- Search for the same entry as before
- Copy the password with ctrl-c
- Copy the password of an other entry displayed from the same search results, with ctrl-c

=> The client is frozen for several seconds, and the password is not copied to the clipboard (In fact, I don't know if the bug first occured on the last or penultimate step)

Anyway, here is the stack trace Java threw me:
(I got the same stack trace at each password-copy-attempt after the first occurence of the bug)

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at fr.securingdata.smartsafe.comm.SmartSafeAppli.getData(SmartSafeAppli.java:216)
        at fr.securingdata.smartsafe.controller.Controls.lambda$static$13(Controls.java:327)
        at fr.securingdata.smartsafe.controller.Action.run(Action.java:25)
        at fr.securingdata.smartsafe.controller.Controls.lambda$static$46(Controls.java:541)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
        at com.sun.javafx.scene.control.ControlAcceleratorSupport.lambda$doAcceleratorInstall$1(ControlAcceleratorSupport.java:165)
        at com.sun.javafx.scene.KeyboardShortcutsHandler.processAccelerators(KeyboardShortcutsHandler.java:347)
        at com.sun.javafx.scene.KeyboardShortcutsHandler.dispatchBubblingEvent(KeyboardShortcutsHandler.java:163)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
        at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
        at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
        at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:410)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
        at com.sun.glass.ui.View.handleKeyEvent(View.java:546)
        at com.sun.glass.ui.View.notifyKey(View.java:966)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:187)
        at java.lang.Thread.run(Unknown Source)

**Comment by securingdata** [comment]
Please add versions of **Client** and **Server** associated to the stack trace.

**Comment by dubicube** [comment]
Server version: **2.0.0**
Client version: **1.0.1**

**Comment by dubicube** [comment]
By pure chance, I discovered just now how to generate on purpose a bug with the exact same stack trace:
- Plug in the key
- Launch the client
- Unlock the key with password
- Click on a group
- Unplug the key
- Click on an entry
- Press ctrl+c
=> The UI does not freeze, but the password is not copied to the clipboard (thankfully!) and I get the same stack trace in the console.

**Comment by dubicube** [comment]
Another weird behavior:
- Plug in the key
- Launch the client
- Unlock the key with password
- Unplug the key before all passwords are loaded
- Search for an entry whose password has not been loaded
- Click on it
- Press ctrl+c
=> The UI completely freeze indefinitely

**Comment by securingdata** [comment]
All these issues are related to lost connection events between computer and token. Handlers for such events will be added in next version.

**Comment by securingdata** [comment]
Fixed in 1.0.2 version
